<a href="https://colab.research.google.com/github/Sharmadevshree3/Python-Libraries-and-codes/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**DIMENSIONS AND SHAPE**

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
a.ndim           #dimensions

1

In [ ]:
b=np.array([[12,13,14],[15,16,17]])

In [ ]:
b.ndim

2

In [ ]:
a.shape        #shape of the array

(5,)

In [ ]:
b.shape

(2, 3)

**LIST AND ITS DIFFERENT FUNCTIONS**

In [ ]:
list = [0,10]

In [ ]:
list

[0, 10]

In [ ]:
c=np.arange(1,10)              #Start,stop(last no. not included),step
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c=np.arange(1,5,2)              #Start,stop(last no. not included),step
c

array([1, 3])

In [ ]:
c=np.linspace(0,1)              #Start,stop,number of value
c

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
c=np.linspace(0,2,8)
c

array([0.        , 0.28571429, 0.57142857, 0.85714286, 1.14285714,
       1.42857143, 1.71428571, 2.        ])

In [ ]:
c=np.logspace(1,3,3)     #ten power : start, stop, points
c

array([  10.,  100., 1000.])

In [ ]:
c=np.logspace(1,5,8)
c

array([1.00000000e+01, 3.72759372e+01, 1.38949549e+02, 5.17947468e+02,
       1.93069773e+03, 7.19685673e+03, 2.68269580e+04, 1.00000000e+05])

In [ ]:
c=np.zeros(5)      #array full of zeros
c

array([0., 0., 0., 0., 0.])

In [ ]:
c=np.zeros([2,3])
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c=np.ones(5)   #arrays full of ones
c

array([1., 1., 1., 1., 1.])

In [ ]:
c=np.ones([2,5])   #2d arrays full of ones
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
c=np.full(10,2)           #array full of values
c

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
c=np.full([2,8],2)           #array full of values
c

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [ ]:
c=np.empty([2,3])
c

array([[0., 0., 0.],
       [0., 0., 0.]])

**RANDOM FUNCTION**

In [ ]:
c=np.random.rand(10,100)      #printing random elements between
c

array([[6.37441266e-01, 2.91346120e-01, 5.38652142e-01, 5.83417532e-01,
        3.67903264e-01, 7.92962894e-01, 8.33313748e-02, 4.97505590e-01,
        4.65299608e-01, 2.46909959e-01, 5.01406598e-01, 5.36018775e-01,
        5.81240481e-02, 6.86307926e-01, 3.40580530e-01, 6.90674935e-01,
        2.28288612e-01, 5.43994815e-01, 7.69754659e-01, 4.80567896e-01,
        4.31678663e-01, 9.72623621e-01, 6.75584573e-01, 8.43779539e-02,
        6.54102126e-01, 4.04801039e-01, 8.14402127e-01, 4.87319979e-01,
        7.68608649e-02, 1.81880004e-02, 6.93134296e-01, 8.41018330e-01,
        2.29697268e-01, 4.51662693e-01, 7.37378305e-01, 4.69802047e-01,
        4.48246484e-01, 7.03914896e-02, 9.10126682e-01, 4.78864779e-01,
        3.72509879e-03, 5.28373418e-01, 9.30507614e-01, 3.90452715e-01,
        9.58251783e-01, 1.08357376e-01, 1.21213398e-01, 7.30432299e-02,
        8.98799620e-01, 2.14898832e-01, 7.82656601e-02, 7.21135604e-01,
        7.93014557e-01, 9.91734868e-01, 8.70447936e-01, 4.829297

In [ ]:
c.size

1000

In [ ]:
np.random.rand(2,3)

array([[0.18297243, 0.87526237, 0.96856225],
       [0.56873155, 0.85868369, 0.9212967 ]])

In [ ]:
np.random.randn(2,3)

array([[ 0.02896425, -0.79935206, -0.88490792],
       [-0.64429813, -0.16803857, -0.31192083]])

In [ ]:
np.random.randint(10,100,size=(2,3))

array([[13, 12, 20],
       [67, 46, 23]])

In [ ]:
c=[1,2,3,4,5]
np.random.choice(c)

np.int64(1)

In [ ]:
d=np.random.shuffle(c)
d

In [ ]:
np.random.permutation(c)

array([3, 4, 5, 2, 1])

**LOGICAL & COMPARISON**

In [ ]:
a=np.array([12,13,1,2,6,12,46,98,46,37,48,20,127,95,684,47,75])

In [ ]:
a.size

17

In [ ]:
d=np.array([12,1,34,23,66,32,4,6,2,66,1,52,535,15,2,62,32])

In [ ]:
d.size

17

In [ ]:
result = np.where(a < 10, "yes", "no")
result

array(['no', 'no', 'yes', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no',
       'no', 'no', 'no', 'no', 'no', 'no', 'no'], dtype='<U3')

In [ ]:
np.greater(a,d)

array([False,  True, False, False, False, False,  True,  True,  True,
       False,  True, False, False,  True,  True, False,  True])

In [ ]:
np.equal(a,d)

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

**SORTING AND SEARCHING**

In [ ]:
a=np.array([12,13,1,2,6,12,46,98,46,37,48,20,127,95,684,47,75])

In [ ]:
np.sort(a)

array([  1,   2,   6,  12,  12,  13,  20,  37,  46,  46,  47,  48,  75,
        95,  98, 127, 684])

In [ ]:
np.argsort(a)        #gives indexes

array([ 2,  3,  4,  0,  5,  1, 11,  9,  8,  6, 15, 10, 16, 13,  7, 12, 14])

In [ ]:
np.searchsorted(a, 6)    #Find insert position

np.int64(4)

In [ ]:
np.nonzero(a)      # Index of non-zero elements

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]),)

**DATA TYPE CHECK**

In [ ]:
c.dtype      #checking data type

dtype('float64')

**RESHAPING ARRAY**

In [ ]:
c=np.array([1,2,3,4,5,6,7,8,9,10])
reshaped=c.reshape(2,5)
reshaped

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
c.astype(float)          #converting element into another datatype

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**INDEXING AND SLICING**

In [ ]:
Marks=np.array([23,2,15,18,8,20,])
Marks

array([23,  2, 15, 18,  8, 20])

In [ ]:
Marks[0]

np.int64(23)

In [ ]:
Marks[-1]

np.int64(20)

In [ ]:
Marks[2:5]

array([15, 18,  8])

In [ ]:
Marks=np.array([23,2,15,18,8,20,])
ind=[0,2]
print(np.take(Marks,ind))

[23 15]


In [ ]:
Marks[0:2]


array([23,  2])

In [ ]:
c=[[2,2],[2,2]]
c

[[2, 2], [2, 2]]

In [ ]:
c[0:2,0:1]

TypeError: list indices must be integers or slices, not tuple

**VIEWS v/s COPIES**

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
copy=arr.copy()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
copy=copy+2
copy

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**ARITHMETIC OPEERATION**

In [ ]:
a=np.array([1,2,3])
b=np.array([3,4,5])

In [ ]:
a+b

array([4, 6, 8])

In [ ]:
a-b

array([-2, -2, -2])

In [ ]:
a%b

array([1, 2, 3])

In [ ]:
a/b

array([0.33333333, 0.5       , 0.6       ])

In [ ]:
a=3.333333333333
np.round(a)

np.float64(3.0)

In [ ]:
np.floor(a)   #gives lower integer

np.float64(3.0)

In [ ]:
np.ceil(a)     #gives higher integer

np.float64(4.0)

In [ ]:
np.trunc(a)      #gives lower integer

np.float64(3.0)

**STATISTICAL METHODS AND FUNCTIONS**

In [ ]:
a=[1,2,3,4,5,6,7,8,9]

In [ ]:
np.mean(a)

np.float64(5.0)

In [ ]:
np.median(a)

np.float64(5.0)

In [ ]:
np.std(a)

np.float64(2.581988897471611)

In [ ]:
np.max(a)

np.int64(9)

In [ ]:
np.min(a)

np.int64(1)

In [ ]:
np.percentile(a,10)

np.float64(1.8)

In [ ]:
np.argmin(a)      #gives index of min

np.int64(0)

In [ ]:
np.argmax(a)      #gives index of max

np.int64(8)

**MATRIX**

In [ ]:
Matrix=np.array([[1,1,2],[2,4,5],[3,6,2]])
Matrix

array([[1, 1, 2],
       [2, 4, 5],
       [3, 6, 2]])

In [ ]:
print(Matrix.transpose())     #transpose

[[1 2 3]
 [1 4 6]
 [2 5 2]]


In [ ]:
np.linalg.inv(Matrix)    #inverse

array([[ 2.        , -0.90909091,  0.27272727],
       [-1.        ,  0.36363636,  0.09090909],
       [ 0.        ,  0.27272727, -0.18181818]])

In [ ]:
np.linalg.det(Matrix)      #determinant

np.float64(-11.000000000000002)

In [ ]:
np.linalg.eig(Matrix)
# Eigen values

EigResult(eigenvalues=array([ 9.42306096,  0.41178558, -2.83484653]), eigenvectors=array([[-0.24205798, -0.89827681, -0.29035222],
       [-0.70443591,  0.43705098, -0.50819241],
       [-0.66721659,  0.0456642 ,  0.81082431]]))

In [ ]:
np.trace(Matrix)

np.int64(7)

In [ ]:
Mat=np.array([[2,3,2],[8,6,5],[2,1,7]])

In [ ]:
np.dot(Matrix,Mat)
# Dot product

array([[14, 11, 21],
       [46, 35, 59],
       [58, 47, 50]])

In [ ]:
np.matmul(Matrix,Mat)
# Matrix multiplication


array([[14, 11, 21],
       [46, 35, 59],
       [58, 47, 50]])

In [ ]:
np.linalg.solve(Matrix,Mat)
# Linear equations

array([[-2.72727273,  0.81818182,  1.36363636],
       [ 1.09090909, -0.72727273,  0.45454545],
       [ 1.81818182,  1.45454545,  0.09090909]])

**VSTACK AND HSTACK**

In [ ]:
arr1=np.array([12,13,1,2,6,12,46,98,46,37,48,20,127,95,684,47,75])

In [ ]:
arr2=np.array([12,1,34,23,66,32,4,6,2,66,1,52,535,15,2,62,32])

In [ ]:
print(np.vstack((arr1,arr2)))

[[ 12  13   1   2   6  12  46  98  46  37  48  20 127  95 684  47  75]
 [ 12   1  34  23  66  32   4   6   2  66   1  52 535  15   2  62  32]]


In [ ]:
print(np.hstack((arr1,arr2))  #the given array is 1d that is why error

SyntaxError: incomplete input (ipython-input-263345898.py, line 1)

#UNIVERSAL FUNCTIONS (ufuncs)
np.sqrt(arr)
=Square root

np.exp(arr)
=Exponential

np.log(arr)
=Logarithm

np.sin(arr)
=Trigonometry

np.abs(arr)
=Absolute values




